export const siteUrl = "https://jiayangimmigration.com"

export type ServicePage = {
  slug: string
  title: string
  titleEn: string
  metaTitle: string
  description: string
  keywords: string[]
  summary: string
  summaryEn: string
  idealFor: string[]
  support: string[]
  faqs: { q: string; a: string }[]
}

export const servicePages: ServicePage[] = [
  {
    slug: "refugee-humanitarian",
    title: "难民与人道主义申请",
    titleEn: "Refugee & Humanitarian Applications",
    metaTitle: "难民与人道主义申请 | Richmond BC 移民顾问 | 佳阳移民",
    description: "佳阳移民为 Richmond BC 及大温哥华客户提供难民、人道主义及复杂移民案件咨询，协助梳理背景、证据和申请路径。",
    keywords: ["难民申请", "人道主义申请", "Richmond immigration consultant", "refugee claim Canada", "humanitarian immigration"],
    summary: "为需要庇护、人道主义考量或复杂移民支持的申请人，提供清晰、谨慎、以材料为核心的案件评估。",
    summaryEn: "Careful case assessment and document-focused support for refugee, humanitarian, and complex Canadian immigration matters.",
    idealFor: ["需要评估难民或人道主义路径", "已有复杂背景或拒签记录", "需要整理证据和时间线"],
    support: ["初步资格和风险评估", "案件背景梳理", "材料清单和证据逻辑", "递交后进度跟进"],
    faqs: [
      { q: "难民或人道主义申请适合所有人吗？", a: "不适合。此类申请需要结合个人经历、风险、证据和加拿大移民法规综合判断，建议先做初步评估。" },
      { q: "如果已有拒签记录，还能咨询吗？", a: "可以。拒签记录会影响策略，但不代表一定没有后续路径，需要先看拒签原因和现有身份情况。" },
      { q: "可以远程沟通吗？", a: "可以。佳阳移民服务加拿大境内外客户，可通过电话、微信或邮件沟通。" },
    ],
  },
  {
    slug: "family-sponsorship",
    title: "家庭团聚移民",
    titleEn: "Family Sponsorship",
    metaTitle: "加拿大家庭团聚移民 | 配偶父母子女担保 | Richmond RCIC 顾问",
    description: "佳阳移民协助加拿大配偶、父母、祖父母和子女团聚担保申请。Richmond BC 持牌 RCIC 顾问，中英双语沟通，首次咨询免费。",
    keywords: ["家庭团聚", "配偶移民", "父母团聚", "spousal sponsorship", "family sponsorship Richmond"],
    summary: "为希望与家人在加拿大团聚的申请人，提供关系证明、担保材料和递交流程支持。",
    summaryEn: "Support for Canadian family sponsorship applications, including spousal, dependent child, and parent sponsorship matters.",
    idealFor: ["配偶或伴侣担保", "子女团聚申请", "父母或祖父母相关咨询"],
    support: ["关系证明材料梳理", "担保人资格评估", "申请表格和文件准备", "补件和进度跟进"],
    faqs: [
      { q: "配偶团聚通常需要多久？", a: "时间会随项目和申请地点变化，常见区间约为 12 到 18 个月，具体以移民局进度为准。" },
      { q: "境外配偶可以申请吗？", a: "可以。境内和境外配偶团聚路径不同，材料重点也不同，建议先评估适合的递交方式。" },
      { q: "第一次咨询收费吗？", a: "首次咨询免费，可先了解基本情况、路径和大致材料要求。" },
    ],
  },
  {
    slug: "work-study-permit",
    title: "学签、工签与毕业工签",
    titleEn: "Study, Work Permit & PGWP",
    metaTitle: "加拿大学签工签 PGWP | 拒签续签与转 PR 规划 | 佳阳移民",
    description: "佳阳移民提供加拿大学签、工签、毕业工签 PGWP、拒签后重新申请和工签转 PR 路径评估。Richmond BC 中文移民顾问。",
    keywords: ["学签", "工签", "毕业工签", "PGWP", "study permit", "work permit Richmond"],
    summary: "围绕学习、工作和身份衔接，帮助申请人理解材料要求、时间节点和后续移民可能性。",
    summaryEn: "Guidance for Canadian study permits, work permits, PGWP, and status planning for students and workers.",
    idealFor: ["准备申请加拿大学签", "毕业后申请 PGWP", "需要工签延期或转换身份"],
    support: ["学习计划和材料审查", "工签类别判断", "身份衔接时间线", "拒签后重新准备建议"],
    faqs: [
      { q: "学签被拒后还能再申请吗？", a: "可以，但需要先分析拒签原因，再决定是否补强学习计划、资金证明或其他材料。" },
      { q: "毕业工签什么时候申请？", a: "通常需要在符合条件的时间窗口内申请，建议毕业前就提前确认材料和时间线。" },
      { q: "工签可以和移民规划一起评估吗？", a: "可以。工签、工作经验和后续移民路径经常需要一起规划。" },
    ],
  },
  {
    slug: "visitor-visa",
    title: "旅游签与探亲签",
    titleEn: "Visitor Visa & Family Visit",
    metaTitle: "加拿大旅游签探亲签 | 拒签后重新申请 | Richmond 移民顾问",
    description: "佳阳移民协助加拿大旅游签、探亲签、父母来加访问和拒签后重新申请，整理邀请信、资金、行程和家庭联系材料。",
    keywords: ["旅游签", "探亲签", "加拿大 visitor visa", "visitor visa Richmond", "family visit visa"],
    summary: "为探亲、旅游、短期访问客户准备更清晰的访问目的、资金和回国约束力材料。",
    summaryEn: "Visitor visa support for tourism, family visits, and short-term travel, with clear documentation planning.",
    idealFor: ["父母或亲友来加拿大探亲", "旅游访问加拿大", "已有拒签记录需要重新准备"],
    support: ["访问目的说明", "邀请信和行程建议", "资金与家庭联系材料", "拒签原因分析"],
    faqs: [
      { q: "探亲签一定需要邀请信吗？", a: "通常建议准备邀请信，并配合申请人的资金、家庭联系和访问计划一起说明。" },
      { q: "旅游签拒签后多久能再申请？", a: "没有固定答案，重点是拒签原因是否已经被解决，材料是否有实质补强。" },
      { q: "可以帮父母申请探亲签吗？", a: "可以。我们会根据父母的情况和邀请方在加拿大的信息准备材料方向。" },
    ],
  },
  {
    slug: "status-extension",
    title: "身份延期与续签",
    titleEn: "Status Extension & Renewal",
    metaTitle: "加拿大身份延期续签 | Visitor Record 工签学签续签 | 佳阳移民",
    description: "佳阳移民协助访客、学生、工人在加拿大延期、续签、恢复身份和身份衔接，帮助客户降低身份过期风险。",
    keywords: ["身份延期", "续签", "visitor record", "status extension Canada", "restore status"],
    summary: "帮助在加拿大境内的客户确认身份有效期、延期路径和递交时间，降低身份中断风险。",
    summaryEn: "Support for Canadian status extension, renewal, and transition planning for visitors, students, and workers.",
    idealFor: ["访客身份即将到期", "学签或工签需要续签", "需要恢复身份或衔接新申请"],
    support: ["身份有效期检查", "延期类别判断", "材料和时间线准备", "递交后跟进"],
    faqs: [
      { q: "身份到期前多久应准备延期？", a: "建议尽早准备，避免临近截止日期时材料不足或递交风险增加。" },
      { q: "已经过期还能处理吗？", a: "需要先看过期时间和身份类别，部分情况可能涉及恢复身份，建议尽快咨询。" },
      { q: "延期期间可以继续留在加拿大吗？", a: "是否可以继续停留取决于递交时间和身份类型，需要按具体情况判断。" },
    ],
  },
  {
    slug: "citizenship-pr-card",
    title: "入籍与枫叶卡更新",
    titleEn: "Citizenship & PR Card Renewal",
    metaTitle: "加拿大入籍与枫叶卡更新 | 居住时间核对 | Richmond 移民顾问",
    description: "佳阳移民协助加拿大入籍申请、枫叶卡更新、居住义务核对和旅行记录整理，服务 Richmond BC 和大温哥华永久居民。",
    keywords: ["加拿大入籍", "枫叶卡更新", "PR card renewal", "Canadian citizenship", "Richmond immigration services"],
    summary: "为永久居民准备入籍或枫叶卡更新材料，梳理居住时间、证明文件和申请细节。",
    summaryEn: "Support for Canadian citizenship applications, PR card renewals, residency obligation review, and document preparation.",
    idealFor: ["准备申请加拿大入籍", "枫叶卡即将过期", "需要确认居住时间或旅行记录"],
    support: ["居住时间初步核对", "申请材料清单", "旅行记录整理", "递交和补件跟进"],
    faqs: [
      { q: "枫叶卡过期是否代表失去永久居民身份？", a: "枫叶卡过期不等于自动失去永久居民身份，但旅行和续卡会受到影响，需要看居住义务是否满足。" },
      { q: "入籍需要准备哪些材料？", a: "通常涉及身份证明、居住时间、语言或其他要求，具体以申请人情况和官方要求为准。" },
      { q: "旅行记录复杂怎么办？", a: "可以先整理出入境记录和护照页，再核对是否满足居住时间要求。" },
    ],
  },
  {
    slug: "entrepreneur-immigration",
    title: "企业家移民",
    titleEn: "Entrepreneur Immigration",
    metaTitle: "企业家移民与创业移民 | BC PNP SUV 咨询 | 佳阳移民",
    description: "佳阳移民为有创业或商业计划的申请人提供企业家移民、BC PNP Entrepreneur、Start-Up Visa 等路径初步评估。",
    keywords: ["企业家移民", "创业移民", "BC PNP Entrepreneur", "Start-Up Visa", "SUV Canada"],
    summary: "为有商业背景、创业计划或投资意向的客户评估可行移民路径和前期准备重点。",
    summaryEn: "Initial pathway assessment for entrepreneurs and business-minded applicants considering Canadian immigration options.",
    idealFor: ["有创业或管理经验", "希望在加拿大开展业务", "想了解 BC PNP 或 SUV 路径"],
    support: ["项目适配度初步评估", "商业背景梳理", "申请路径比较", "材料准备方向"],
    faqs: [
      { q: "企业家移民一定需要商业计划吗？", a: "多数商业类项目都需要清晰的商业方向和证明材料，具体取决于项目要求。" },
      { q: "SUV 和省提名企业家项目有什么不同？", a: "两者定位、要求和流程不同，需要结合申请人的背景、资源和目标选择。" },
      { q: "可以先做初步评估吗？", a: "可以。建议先评估个人背景、资产、语言、商业计划和时间预期。" },
    ],
  },
  {
    slug: "investor-immigration",
    title: "投资类移民评估",
    titleEn: "Investor Immigration Assessment",
    metaTitle: "投资类移民评估 | 加拿大省提名投资项目 | 佳阳移民",
    description: "佳阳移民为具备资产实力和投资意向的申请人评估加拿大投资类、省提名及商业移民路径。",
    keywords: ["投资移民", "省提名投资", "加拿大商业移民", "investor immigration", "business immigration Canada"],
    summary: "帮助申请人从资产、商业经验、地区选择和项目要求出发，判断投资类移民路径是否适合。",
    summaryEn: "Assessment for investor and business immigration pathways based on assets, business experience, and project fit.",
    idealFor: ["具备一定资产和商业经验", "考虑加拿大投资或商业项目", "需要比较不同省份路径"],
    support: ["背景和资产条件初评", "项目要求说明", "地区和路径比较", "材料准备建议"],
    faqs: [
      { q: "加拿大还有传统投资移民吗？", a: "项目会随政策变化，具体需要根据当前可行的省提名或商业类路径评估。" },
      { q: "投资金额越高越容易获批吗？", a: "不一定。项目匹配、商业经验、真实性和材料质量都很重要。" },
      { q: "可以只做路径咨询吗？", a: "可以。初步咨询可以先判断是否值得继续深入准备。" },
    ],
  },
  {
    slug: "express-entry",
    title: "快速通道 Express Entry",
    titleEn: "Express Entry",
    metaTitle: "Express Entry 快速通道 | CRS 评估与提分策略 | Richmond RCIC 顾问",
    description: "佳阳移民提供 Express Entry 快速通道、CRS 分数评估、提分策略、省提名方向和永久居民申请支持。首次咨询免费。",
    keywords: ["Express Entry", "快速通道", "CRS 评分", "联邦技术移民", "Richmond Express Entry consultant"],
    summary: "为技术移民申请人评估 CRS 分数、语言学历工作经验和可行提分方向，规划永久居民申请路径。",
    summaryEn: "Express Entry support including CRS assessment, score-improvement planning, and permanent residence application guidance.",
    idealFor: ["有加拿大或海外工作经验", "想评估 CRS 分数", "准备申请联邦技术移民或相关省提名"],
    support: ["CRS 初步评估", "提分策略建议", "材料清单和时间线", "递交后跟进"],
    faqs: [
      { q: "Express Entry 主要看什么？", a: "主要看 CRS 综合评分，包括年龄、学历、语言、工作经验、加拿大经历和其他加分因素。" },
      { q: "分数不够还能做什么？", a: "可以评估语言提分、学历认证、工作经验、省提名或其他路径是否可行。" },
      { q: "快速通道一定 6 个月出结果吗？", a: "6 个月通常指部分完整申请递交后的目标处理时间，实际仍会受案件和移民局进度影响。" },
    ],
  },
  {
    slug: "spousal-sponsorship",
    title: "加拿大配偶团聚移民",
    titleEn: "Spousal Sponsorship",
    metaTitle: "加拿大配偶团聚移民 | Richmond RCIC 持牌顾问 | 首次咨询免费",
    description: "佳阳移民协助加拿大配偶团聚、境内配偶担保、境外配偶担保和关系证明材料准备。Richmond BC 持牌 RCIC 顾问，首次咨询免费。",
    keywords: ["配偶团聚移民", "加拿大配偶担保", "spousal sponsorship", "inland spousal sponsorship", "outland spousal sponsorship", "Richmond RCIC"],
    summary: "为希望担保配偶或伴侣来加拿大团聚的申请人，梳理境内、境外递交路径和关系证明材料重点。",
    summaryEn: "Support for Canadian spousal sponsorship applications, including inland and outland pathways and relationship evidence planning.",
    idealFor: ["加拿大公民或永久居民担保配偶", "需要准备关系证明材料", "想判断境内或境外递交更合适"],
    support: ["担保人资格初步评估", "境内/境外路径比较", "关系证明材料清单", "表格准备和递交后跟进"],
    faqs: [
      { q: "配偶团聚移民通常需要多久？", a: "常见处理时间约为 12 到 18 个月，实际会受递交方式、材料完整度和移民局进度影响。" },
      { q: "境内和境外配偶担保有什么区别？", a: "两者在递交位置、申请人是否在加拿大、工签安排和流程细节上不同，建议先按身份和旅行计划评估。" },
      { q: "关系证明需要准备哪些材料？", a: "通常包括结婚证、合照、聊天记录、共同居住或财务证明、亲友证明等，具体要按关系情况整理。" },
      { q: "配偶团聚被拒后还能再申请吗？", a: "可以，但需要先分析拒签原因，例如关系真实性、材料不足或表格问题，再重新设计证明材料和递交策略。" },
      { q: "配偶团聚需要担保人达到最低收入吗？", a: "多数配偶担保不要求像父母担保那样的最低收入门槛，但担保人仍需证明有基本能力履行担保责任。" },
    ],
  },
  {
    slug: "parent-sponsorship",
    title: "加拿大父母团聚移民",
    titleEn: "Parent & Grandparent Sponsorship",
    metaTitle: "加拿大父母团聚移民 | 父母祖父母担保 | Richmond 移民顾问",
    description: "佳阳移民协助父母、祖父母团聚担保申请和超级签证路径评估，帮助担保人确认收入、材料和时间线。Richmond BC 中文移民服务。",
    keywords: ["父母团聚移民", "父母担保", "祖父母担保", "parent sponsorship Canada", "grandparent sponsorship", "super visa"],
    summary: "为希望担保父母或祖父母来加拿大团聚的家庭，评估收入要求、家庭人数、材料准备和替代路径。",
    summaryEn: "Guidance for parent and grandparent sponsorship, income review, document planning, and alternative family visit pathways.",
    idealFor: ["想担保父母或祖父母移民", "需要确认担保收入是否达标", "想比较团聚担保和超级签证"],
    support: ["担保人收入和家庭人数初评", "申请资格和时间线说明", "材料清单准备", "超级签证替代路径建议"],
    faqs: [
      { q: "父母团聚一定可以随时递交吗？", a: "不一定。父母和祖父母担保项目通常受官方开放安排影响，需要根据当期政策判断是否可递交。" },
      { q: "收入不够还能担保父母吗？", a: "收入要求是关键条件之一。如果暂时不满足，可以评估共同签署人、等待下一年收入或超级签证等路径。" },
      { q: "超级签证和父母团聚有什么不同？", a: "超级签证是临时居民签证，父母团聚是永久居民路径，两者目标、材料和审理逻辑不同。" },
      { q: "父母团聚需要看几年的收入？", a: "通常需要按官方要求核对担保人近年收入和家庭人数，具体年限和金额需以当期政策为准。" },
      { q: "父母团聚没有开放时怎么办？", a: "可以先评估超级签证、普通探亲签或后续担保准备，提前整理收入、家庭人数和身份材料。" },
    ],
  },
  {
    slug: "study-permit",
    title: "加拿大学签申请",
    titleEn: "Canada Study Permit",
    metaTitle: "加拿大学签申请 | 拒签后重新申请评估 | Richmond 中文顾问",
    description: "佳阳移民协助加拿大学签申请、学习计划、资金证明和拒签后重新递交评估。Richmond BC RCIC 持牌顾问，支持中英双语沟通。",
    keywords: ["加拿大学签", "学签申请", "study permit Canada", "study permit refusal", "Richmond study permit consultant"],
    summary: "帮助学生和家庭围绕录取、学习计划、资金证明和未来规划，准备更清晰的加拿大学签材料。",
    summaryEn: "Study permit support for students, including study plans, financial proof, refusal review, and document preparation.",
    idealFor: ["准备申请加拿大学签", "需要完善学习计划和资金材料", "学签被拒后想重新申请"],
    support: ["学习计划方向建议", "资金证明材料梳理", "申请表格和文件检查", "拒签原因初步分析"],
    faqs: [
      { q: "学签最重要的材料是什么？", a: "通常包括录取信、学习计划、资金证明、身份文件和与申请人背景匹配的解释材料。" },
      { q: "学签被拒后可以马上再申请吗？", a: "可以重新申请，但重点是先分析拒签原因，再补强材料，而不是简单重复递交。" },
      { q: "大龄申请人还能申请学签吗？", a: "可以，但学习目的、职业背景和回国约束力需要解释得更清楚。" },
      { q: "学签资金证明要准备多少？", a: "资金证明需要覆盖学费、生活费和相关开支，并与家庭收入来源、存款历史和学习计划相互匹配。" },
      { q: "学签学习计划怎么写更合理？", a: "学习计划应解释为什么选择该学校和专业、与过往背景的关系、毕业后的合理安排，以及为什么会遵守签证条件。" },
    ],
  },
  {
    slug: "work-permit",
    title: "加拿大工签申请",
    titleEn: "Canada Work Permit",
    metaTitle: "加拿大工签申请 | 工签续签与转 PR 规划 | Richmond RCIC 顾问",
    description: "佳阳移民提供加拿大工签申请、工签续签、雇主支持类工签和工签转 PR 路径评估。Richmond BC 持牌移民顾问，首次咨询免费。",
    keywords: ["加拿大工签", "工签申请", "工签续签", "work permit Canada", "work permit to PR", "Richmond immigration consultant"],
    summary: "为在加拿大工作或准备来加拿大工作的申请人，评估工签类别、雇主材料、身份衔接和后续 PR 路径。",
    summaryEn: "Work permit guidance including permit category review, employer-supported documents, renewals, and PR pathway planning.",
    idealFor: ["需要申请或续签加拿大工签", "有雇主支持或 LMIA 相关问题", "想了解工签转 PR 路径"],
    support: ["工签类别初步判断", "雇主材料方向说明", "身份衔接时间线", "PR 路径初步规划"],
    faqs: [
      { q: "加拿大工签有哪些常见类型？", a: "常见包括雇主支持类工签、开放工签、配偶工签、毕业工签等，具体要按申请人背景判断。" },
      { q: "工签快到期怎么办？", a: "建议尽早评估续签或转换身份路径，避免临近到期才发现材料或资格不足。" },
      { q: "工签可以直接转 PR 吗？", a: "工签本身不是永久居民身份，但工作经验、雇主支持、省提名或 Express Entry 可能帮助规划 PR。" },
      { q: "工签快过期还能续吗？", a: "需要先看工签类型、雇主支持、身份到期日和是否仍符合资格。越早评估，越容易保留身份衔接空间。" },
      { q: "配偶可以申请开放工签吗？", a: "部分情况下可以，但要看主申请人的身份、学习或工作条件以及当期政策要求。" },
    ],
  },
  {
    slug: "pgwp",
    title: "加拿大毕业工签 PGWP",
    titleEn: "Post-Graduation Work Permit",
    metaTitle: "加拿大毕业工签 PGWP 申请 | 留学生工签与 PR 规划 | 佳阳移民",
    description: "佳阳移民协助加拿大毕业工签 PGWP 申请、材料准备、毕业后身份衔接和后续 PR 路径规划，服务 Richmond BC 及大温留学生。",
    keywords: ["毕业工签", "PGWP", "加拿大 PGWP", "post graduation work permit", "留学生工签", "Richmond PGWP consultant"],
    summary: "为加拿大留学生毕业后的工签申请、时间窗口、材料准备和移民路径衔接提供支持。",
    summaryEn: "PGWP support for international graduates, including application timing, document planning, and PR pathway transition.",
    idealFor: ["即将毕业的加拿大留学生", "需要申请 PGWP", "想用毕业工签规划 PR"],
    support: ["毕业工签资格初评", "申请时间窗口提醒", "毕业文件和身份材料检查", "后续 PR 路径建议"],
    faqs: [
      { q: "PGWP 什么时候申请？", a: "通常需要在符合条件的毕业文件出具后，在规定时间窗口内递交，建议毕业前先确认材料。" },
      { q: "毕业工签长度怎么判断？", a: "通常与课程长度和学校资格有关，具体需要结合学习项目和官方规则判断。" },
      { q: "PGWP 后怎么转 PR？", a: "常见方向包括 Canadian Experience Class、省提名或其他技术移民路径，需要结合工作、语言和学历规划。" },
      { q: "PGWP 过期后还能恢复身份吗？", a: "是否能恢复取决于过期时间、当前身份和可用申请类型，建议尽快评估，不要等到身份问题扩大。" },
      { q: "毕业后还没拿到工签可以工作吗？", a: "是否可以工作取决于递交时间、学习状态和申请条件，需要按具体情况判断，不能一概而论。" },
    ],
  },
  {
    slug: "pr-card-renewal",
    title: "加拿大枫叶卡更新",
    titleEn: "PR Card Renewal",
    metaTitle: "加拿大枫叶卡更新 | 居住义务核对 | Richmond 移民顾问",
    description: "佳阳移民协助加拿大永久居民枫叶卡更新、居住义务核对、旅行记录整理和材料准备。Richmond BC 中文移民服务。",
    keywords: ["枫叶卡更新", "PR card renewal", "永久居民卡更新", "residency obligation", "Richmond PR card renewal"],
    summary: "帮助永久居民核对居住义务、旅行记录和续卡材料，降低因记录复杂带来的递交风险。",
    summaryEn: "PR card renewal support including residency obligation review, travel history organization, and document preparation.",
    idealFor: ["枫叶卡即将到期或已过期", "旅行记录复杂", "需要确认是否满足居住义务"],
    support: ["居住天数初步核对", "旅行记录整理", "续卡材料清单", "复杂情况风险提示"],
    faqs: [
      { q: "枫叶卡过期还能续吗？", a: "枫叶卡过期不代表自动失去永久居民身份，但续卡前需要看居住义务和旅行记录。" },
      { q: "人在加拿大境外怎么办？", a: "境外情况可能涉及 PRTD 或其他安排，建议先确认所在地、旅行计划和居住义务。" },
      { q: "旅行记录不清楚可以处理吗？", a: "可以先根据护照、出入境记录和个人记忆整理，再核对是否满足要求。" },
      { q: "枫叶卡过期还能回加拿大吗？", a: "人在境外时可能需要评估 PRTD 或其他入境安排；人在加拿大境内则重点看续卡和居住义务。" },
      { q: "居住时间不够还能续枫叶卡吗？", a: "居住义务不足会带来风险，需要先核对天数、例外情况和个人旅行记录，再判断处理方向。" },
    ],
  },
  {
    slug: "citizenship",
    title: "加拿大入籍申请",
    titleEn: "Canadian Citizenship Application",
    metaTitle: "加拿大入籍申请 | 居住时间与旅行记录核对 | 佳阳移民",
    description: "佳阳移民协助加拿大入籍申请、居住时间核对、旅行记录整理和申请材料准备。Richmond BC 持牌 RCIC 顾问，中英双语服务。",
    keywords: ["加拿大入籍", "入籍申请", "Canadian citizenship", "citizenship application Canada", "Richmond citizenship consultant"],
    summary: "为准备申请加拿大公民身份的永久居民，核对居住时间、旅行记录、身份文件和申请材料。",
    summaryEn: "Citizenship application support including physical presence review, travel history, identity documents, and application preparation.",
    idealFor: ["准备申请加拿大入籍", "需要核对居住时间", "旅行记录或身份文件较复杂"],
    support: ["居住时间初步核算", "旅行记录整理", "入籍材料清单", "递交前文件检查"],
    faqs: [
      { q: "加拿大入籍需要住满多久？", a: "通常需要满足官方规定的实际居住时间要求，并结合申请前的时间范围计算。" },
      { q: "旅行很多会影响入籍吗？", a: "频繁旅行本身不一定影响，但需要准确计算在加拿大实际居住天数并准备记录。" },
      { q: "入籍申请可以自己递交吗？", a: "可以。若旅行记录复杂、材料不确定或希望减少错误，可以先做材料检查和路径评估。" },
      { q: "入籍旅行记录算错怎么办？", a: "旅行记录会影响居住时间计算，建议递交前用护照、出入境记录和个人行程逐项核对。" },
      { q: "入籍考试或语言材料需要提前准备吗？", a: "需要根据申请人年龄、语言证明和官方要求判断，材料准备阶段就应确认是否符合要求。" },
    ],
  },
]

export function getServicePage(slug: string) {
  return servicePages.find((service) => service.slug === slug)
}
